# Generated by Django 4.1.5 on 2023-02-04 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_books",
                    models.CharField(
                        default=0, max_length=255, verbose_name="Quantidade"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timetable",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horário"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Compra"), ("2", "Venda")],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "book",
                    models.ManyToManyField(
                        through="transaction.Book_Transaction", to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book_transaction",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transaction",
            ),
        ),
    ]
