# Generated by Django 4.1.5 on 2023-02-04 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Nome"),
                ),
                (
                    "quantity_pages",
                    models.CharField(max_length=255, verbose_name="Quantidade de Pg."),
                ),
                (
                    "book_cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="livros/", verbose_name="Capa"
                    ),
                ),
                (
                    "status_book",
                    models.CharField(
                        choices=[
                            ("Novo", "Novo"),
                            ("Usado", "Usado"),
                            ("Seminovo", "Seminovo"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("author", models.CharField(max_length=255, verbose_name="Autor")),
                ("note", models.CharField(max_length=255, verbose_name="Observação")),
                ("year", models.CharField(max_length=255, verbose_name="Ano")),
                ("price", models.CharField(max_length=255, verbose_name="Preço")),
                (
                    "quantity",
                    models.CharField(max_length=255, verbose_name="Quantidade"),
                ),
                ("synopsis", models.CharField(max_length=255, verbose_name="Sinopse")),
                (
                    "publishing_company",
                    models.CharField(max_length=255, verbose_name="Editora"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book_Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_books",
                    models.CharField(
                        default=0, max_length=255, verbose_name="Quantidade"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Livro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_books",
                    models.CharField(
                        default=0, max_length=255, verbose_name="Quantidade"
                    ),
                ),
                (
                    "book",
                    models.ManyToManyField(through="books.Book_Cart", to="books.book"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book_cart",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.cart",
                verbose_name="Carrinho",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
