# Generated by Django 4.1.5 on 2023-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Capa"
            ),
        ),
    ]
