# Generated by Django 4.1.5 on 2023-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status_book",
            field=models.CharField(
                choices=[
                    ("Novo", "Novo"),
                    ("Usado", "Usado"),
                    ("Seminovo", "Seminovo"),
                ],
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
